name: Next.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Your package.json is compatible with Node 18+

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build the Next.js app
        run: npm run build
